apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- ingress.yaml
- deployment.yaml
- service.yaml

# labels added to all Resources
commonLabels:
  app: inlets

images:
- name: inlets/inlets
  newTag: 2.6.3

secretGenerator:
- name: inlets-token
  literals:
  - TOKEN=4e10d81d8b01cc95ade6be31f2bbbc0d10bb1dfd
  
generatorOptions:
  disableNameSuffixHash: true